### ISSUE TITLE
Default increment of SWT ScrollBar is 1px

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-widgets#43]
When clicking on the arrows of an SWT scrollbar, as used in a ScrolledComposite, it only scrolls by 1px per default. This is an open issue in SWT, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=367208
While it is possible to set the increment size on the ScrollBar directly, there is often no easy way to access it from outside. 
However, there is an opportunity to add a workaround for this in 
org.jowidgets.spi.impl.swt.common.widgets.ScrollCompositeImpl

**Comment by herrgrossmann** [comment]
Fixed in 0.64.0

**Comment by herrgrossmann** [comment]
Commit 6bd816e leads to unnecessary layouting when scroll Composite will be resized
