### ISSUE TITLE
Verify of double values is to strict

### ISSUE THREAD

**Issue by herrgrossmann** [jo-source/jo-widgets#52]
Assuming colon (,) is the decimal separator and dot (.) is the grouping separator:

When editing an IInputField with double converter that has the value 1,8 e.g. and set the cursor to the beginning (|1,8) it is not possible to remove the '1' with help of the DEL key, because the currently used verifying does not allow the value ',8' and so the modification is rejected

Expected:

The verifying for floating piont numbers should be more tollerant, so e.g. ,8 should be allowed and parsed to 0,8. Grouping separator should be allowed at any place for input. They will be ignored for parsing anyway ( e.g. 1.23.24353.35,21342.234 should be valid). The input if non numeric char should be rejected anymore (e.g. 123Horst34) must not be possible to enter. Parse errors should be validated (not verified with blocking key), so e.g. 12,1323,24 will lead to an validation error but is possible to enter into the input field.

**Comment by NielsBeuck** [comment]
Review Comments: 

AbstractFloatingPointNumberConverter:
Zeile 73:
 Bin über das E in dem Ausdruck gestolpert. Geht es um die exponentialschreibweise?
 Dann ist damit einiges falsch:
    man kann z.B. mehr als ein E schreiben oder nach dem E einfach aufhören
    und Nachkommastellen im Exponenten sind auch unüblich
    oder wird das noch woanders abgefangen?
    Und ein kleines e sollte auch erlaubt sein.
Zeile 117 und 180:
 Ich rieche Redundanz.

StringUtilsTest
 Zeile 63 -66:
 ‚e‘ statt „e“ um auch die char variante zu testen?

**Comment by herrgrossmann** [comment]
Fixed in 0.66.0
