### ISSUE TITLE
The NatTable selection behaviour is not consitent with that of swt or windows explorer

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-widgets#60]
The selection behaviour of the nattable based table differs from the swt-table and standard windows explorer bahaviour in three regards:
1. A rightclick into the nattable does not select the row under the mouse cursor.
2. Mouse down on one of several selected rows in the nattable immediately selects that one row, instead of waiting for a possible mouse drag event (the swt-table and the windows explorer only select on mouse up when clicking on an already selected row.)
3. When holding down the left mouse button, the nattable enters a multi selection mode which interferes with drag&drop functionality.

**Comment by herrgrossmann** [comment]
Will be available with version 0.69.0
