### ISSUE TITLE
Mouseover tooltip for partially visible cell content in the NatTable missing

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-widgets#61]
The SWT table does show a tooltip when hovering over a cell with partially hidden content (indicated by ...),
the Nattable based table implementation currently does not.

**Comment by herrgrossmann** [comment]
I found this link but it not really helps:
https://www.eclipse.org/forums/index.php/t/1081954/

**Comment by herrgrossmann** [comment]
Will be available with version 0.69.0
