### ISSUE TITLE
After hiding all columns in a NatTable based table, the context menu to show them again is not accessible

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-widgets#74]
When you hide all columns in a table (at least if it is a Nattable based jo-client-platform BeanTable), there is no way to show them again. It is simply not possible anymore to open a context menu.
It should always be possible to access the settings dialog of the table via the context menu, even when clicking outside of a column.

**Comment by herrgrossmann** [comment]
Problen only occurs with nat table spi implementation

**Comment by herrgrossmann** [comment]
Fix available with 0.74.0
